package org.scbit.lsbi.renren.pojo;

// Generated 2012-8-5 12:13:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbCity generated by hbm2java
 */
public class TbCity implements java.io.Serializable {

	private String id;
	private TbProvince tbProvince;
	private String name;
	private Set tbCounties = new HashSet(0);

	public TbCity() {
	}

	public TbCity(String id) {
		this.id = id;
	}

	public TbCity(String id, TbProvince tbProvince, String name, Set tbCounties) {
		this.id = id;
		this.tbProvince = tbProvince;
		this.name = name;
		this.tbCounties = tbCounties;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TbProvince getTbProvince() {
		return this.tbProvince;
	}

	public void setTbProvince(TbProvince tbProvince) {
		this.tbProvince = tbProvince;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTbCounties() {
		return this.tbCounties;
	}

	public void setTbCounties(Set tbCounties) {
		this.tbCounties = tbCounties;
	}

}
