package org.scbit.lsbi.renren.pojo;

// Generated 2012-8-5 12:13:26 by Hibernate Tools 3.4.0.CR1

/**
 * TbCounty generated by hbm2java
 */
public class TbCounty implements java.io.Serializable {

	private String id;
	private TbCity tbCity;
	private String name;

	public TbCounty() {
	}

	public TbCounty(String id) {
		this.id = id;
	}

	public TbCounty(String id, TbCity tbCity, String name) {
		this.id = id;
		this.tbCity = tbCity;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TbCity getTbCity() {
		return this.tbCity;
	}

	public void setTbCity(TbCity tbCity) {
		this.tbCity = tbCity;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
