package org.scbit.lsbi.renren.pojo;

// Generated 2012-8-5 12:13:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbProvince generated by hbm2java
 */
public class TbProvince implements java.io.Serializable {

	private String id;
	private String name;
	private Set tbCities = new HashSet(0);

	public TbProvince() {
	}

	public TbProvince(String id) {
		this.id = id;
	}

	public TbProvince(String id, String name, Set tbCities) {
		this.id = id;
		this.name = name;
		this.tbCities = tbCities;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTbCities() {
		return this.tbCities;
	}

	public void setTbCities(Set tbCities) {
		this.tbCities = tbCities;
	}

}
