package org.scbit.lsbi.renren.pojo;

// Generated 2012-7-25 20:47:04 by Hibernate Tools 3.4.0.CR1

/**
 * TbWeatherId generated by hbm2java
 */
public class TbWeatherId implements java.io.Serializable {

	private String woe;
	private String date;

	public TbWeatherId() {
	}

	public TbWeatherId(String woe, String date) {
		this.woe = woe;
		this.date = date;
	}

	public String getWoe() {
		return this.woe;
	}

	public void setWoe(String woe) {
		this.woe = woe;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbWeatherId))
			return false;
		TbWeatherId castOther = (TbWeatherId) other;

		return ((this.getWoe() == castOther.getWoe()) || (this.getWoe() != null
				&& castOther.getWoe() != null && this.getWoe().equals(
				castOther.getWoe())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getWoe() == null ? 0 : this.getWoe().hashCode());
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
