package org.scbit.lsbi.renren.pojo;

// Generated 2012-7-25 20:47:04 by Hibernate Tools 3.4.0.CR1

/**
 * TbWeather generated by hbm2java
 */
public class TbWeather implements java.io.Serializable {

	private TbWeatherId id;
	private String cityName;
	private String cityCountry;
	private String tmpLow;
	private String tmpHigh;
	private String windSpeed;
	private String humidity;
	private String visiblity;
	private String pressure;
	private String sunrise;
	private String latitude;
	private String longitude;
	private String imgUrl;

	public TbWeather() {
	}

	public TbWeather(TbWeatherId id) {
		this.id = id;
	}

	public TbWeather(TbWeatherId id, String cityName, String cityCountry,
			String tmpLow, String tmpHigh, String windSpeed, String humidity,
			String visiblity, String pressure, String sunrise, String latitude,
			String longitude, String imgUrl) {
		this.id = id;
		this.cityName = cityName;
		this.cityCountry = cityCountry;
		this.tmpLow = tmpLow;
		this.tmpHigh = tmpHigh;
		this.windSpeed = windSpeed;
		this.humidity = humidity;
		this.visiblity = visiblity;
		this.pressure = pressure;
		this.sunrise = sunrise;
		this.latitude = latitude;
		this.longitude = longitude;
		this.imgUrl = imgUrl;
	}

	public TbWeatherId getId() {
		return this.id;
	}

	public void setId(TbWeatherId id) {
		this.id = id;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getCityCountry() {
		return this.cityCountry;
	}

	public void setCityCountry(String cityCountry) {
		this.cityCountry = cityCountry;
	}

	public String getTmpLow() {
		return this.tmpLow;
	}

	public void setTmpLow(String tmpLow) {
		this.tmpLow = tmpLow;
	}

	public String getTmpHigh() {
		return this.tmpHigh;
	}

	public void setTmpHigh(String tmpHigh) {
		this.tmpHigh = tmpHigh;
	}

	public String getWindSpeed() {
		return this.windSpeed;
	}

	public void setWindSpeed(String windSpeed) {
		this.windSpeed = windSpeed;
	}

	public String getHumidity() {
		return this.humidity;
	}

	public void setHumidity(String humidity) {
		this.humidity = humidity;
	}

	public String getVisiblity() {
		return this.visiblity;
	}

	public void setVisiblity(String visiblity) {
		this.visiblity = visiblity;
	}

	public String getPressure() {
		return this.pressure;
	}

	public void setPressure(String pressure) {
		this.pressure = pressure;
	}

	public String getSunrise() {
		return this.sunrise;
	}

	public void setSunrise(String sunrise) {
		this.sunrise = sunrise;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
	
	public boolean isWhole() {
		if(!id.getWoe().equals("")&&!cityName.equals("")&&!cityCountry.equals("")&&!id.getDate().equals("")&&!imgUrl.equals("")&&!tmpHigh.equals("")&&!tmpLow.equals("")) {
			return true;
		}else {
			return false;
		}
	}

}
